class A3RP_Settings {
	/**
	* Buildings the player can spawn in
	*/
	buildings_spawn[] = {
		"Land_i_Shop_01_V3_F",
		"Land_i_Shop_02_V1_F",
		"Land_i_Shop_01_V1_F"
	};

	/**
	* Buildings that can be bought
	*/
	buildings_buyable[] = {
		"Land_Offices_01_V1_F",
		"Land_u_Addon_02_V1_F",
		"Land_i_Addon_02_V1_F",
		"Land_i_Garage_V1_F",
		"Land_i_Garage_V2_F",
		"Land_Metal_Shed_F",
		"Land_i_House_Big_01_V1_F",
		"Land_i_House_Big_01_V2_F",
		"Land_i_House_Big_01_V3_F",
		"Land_u_House_Big_01_V1_F",
		"Land_i_House_Big_02_V1_F",
		"Land_i_House_Big_02_V2_F",
		"Land_i_House_Big_02_V3_F",
		"Land_u_House_Big_02_V1_F",
		"Land_i_Shop_01_V1_F",
		"Land_i_Shop_01_V2_F",
		"Land_i_Shop_01_V3_F",
		"Land_u_Shop_01_V1_F",
		"Land_i_Shop_02_V1_F",
		"Land_i_Shop_02_V2_F",
		"Land_i_Shop_02_V3_F",
		"Land_u_Shop_02_V1_F",
		"Land_i_House_Small_01_V1_F",
		"Land_i_House_Small_01_V2_F",
		"Land_i_House_Small_01_V3_F",
		"Land_u_House_Small_01_V1_F",
		"Land_i_House_Small_02_V1_F",
		"Land_i_House_Small_02_V2_F",
		"Land_i_House_Small_02_V3_F",
		"Land_u_House_Small_02_V1_F",
		"Land_i_House_Small_03_V1_F",
		"Land_Slum_House01_F",
		"Land_Slum_House02_F",
		"Land_Slum_House03_F",
		"Land_i_Stone_HouseBig_V1_F",
		"Land_i_Stone_HouseBig_V2_F",
		"Land_i_Stone_HouseBig_V3_F",
		"Land_d_Stone_HouseBig_V1_F",
		"Land_i_Stone_Shed_V1_F",
		"Land_i_Stone_Shed_V2_F",
		"Land_i_Stone_Shed_V3_F",
		"Land_i_Stone_HouseSmall_V1_F",
		"Land_i_Stone_HouseSmall_V2_F",
		"Land_i_Stone_HouseSmall_V3_F",
		"Land_Hangar_F",
		"Land_i_Shed_Ind_F",
		"Land_i_Barracks_V1_F",
		"Land_i_Barracks_V2_F",
		"Land_u_Barracks_V2_F",
		"Land_Cargo_House_V1_F",
		"Land_Cargo_House_V2_F",
		"Land_Cargo_House_V3_F",
		"Land_MilOffices_V1_F",
		"Land_TentHangar_V1_F",
		"Land_GH_House_1_F",
		"Land_GH_House_2_F"
	};
};